import { randomInt } from "node:crypto";
import { mkdirSync } from "node:fs";
import { readJsonFileSync as readFileSync, writeJsonFile as writeFileSync } from "../storage/atomic-json.js";
import { dirname } from "node:path";
import type { DiscordUser } from "@iris/shared";
import type { ServerEnv } from "../env.js";
import { AppError } from "../errors.js";
import { reserveCasinoBet, settleCasinoReservation } from "../services/casino-economy.js";
type FetchLike=(input:string|URL,init?:RequestInit)=>Promise<Response>;type Phase="reserving"|"settling"|"settled";type Card=(number|string)[][];
export interface BingoRound{drawId:string;discordUserId:string;bet:number;card:Card;draws:number[];lines:string[];payout:number|null;wallet:number|null;phase:Phase}
export interface BingoStore{load():BingoRound[];save(rounds:BingoRound[]):void}
export class FileBingoStore implements BingoStore{constructor(private readonly path:string){}load(){try{const v:unknown=JSON.parse(readFileSync(this.path,"utf8"));if(!Array.isArray(v))throw new Error("Bingo state invalid");return v as BingoRound[]}catch(e){if(e instanceof Error&&"code" in e&&e.code==="ENOENT")return [];throw e}}save(r:BingoRound[]){mkdirSync(dirname(this.path),{recursive:true});writeFileSync(this.path,JSON.stringify(r),"utf8")}}
export class BingoService{private readonly rounds:Map<string,BingoRound>;constructor(private readonly o:{env:ServerEnv;fetch:FetchLike;store:BingoStore}){this.rounds=new Map(o.store.load().map(r=>[r.drawId,r]))}async reconcileAll(){for(const r of this.rounds.values())if(r.phase!=="settled")await this.resume(r)}async play(u:DiscordUser,id:string,bet:number){if(!valid(id)||![100,500,1000,2500,5000].includes(bet))throw new AppError(400,"bad_request","Bingo ticket invalid.");const old=this.rounds.get(id);if(old){if(old.discordUserId!==u.id||old.bet!==bet)throw new AppError(409,"casino_transaction_conflict","Bingo ticket does not match.");await this.resume(old);return old}const r:BingoRound={drawId:id,discordUserId:u.id,bet,card:card(),draws:[],lines:[],payout:null,wallet:null,phase:"reserving"};this.rounds.set(id,r);this.save();await this.resume(r);return r}private async resume(r:BingoRound){if(r.phase==="reserving"){const x=await reserveCasinoBet({transactionId:`bingo-${r.drawId}`,discordUserId:r.discordUserId,sessionId:`bingo-${r.drawId}`,game:"bingo",bet:r.bet},this.o.env,this.o.fetch);r.wallet=x.wallet;const pool=shuffle(Array.from({length:75},(_,i)=>i+1));const marked=new Set(["2-2"]);for(let i=0;i<35;i++){const n=pool[i]!;r.draws.push(n);mark(r.card,marked,n);r.lines=lines(marked);if(r.lines.length)break}const at=r.draws.length,multi=r.lines.length?(at<=18?24:at<=22?10:at<=26?4:at<=30?2:.8)*Math.max(1,r.lines.length):0;r.payout=Math.floor(r.bet*multi);r.phase="settling";this.save()}if(r.phase==="settling"){const x=await settleCasinoReservation(`bingo-${r.drawId}`,{payout:r.payout??0},this.o.env,this.o.fetch);r.wallet=x.wallet;r.phase="settled";this.save()}}private save(){this.o.store.save([...this.rounds.values()])}}
function valid(v:string){return /^[A-Za-z0-9:_.-]{1,128}$/.test(v)}function shuffle<T>(a:T[]){for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j]!,a[i]!]}return a}function card():Card{const ranges:[number,number][]=[[1,15],[16,30],[31,45],[46,60],[61,75]];const c:Card=ranges.map(([start,end])=>shuffle(Array.from({length:end-start+1},(_,i)=>start+i)).slice(0,5));c[2]![2]="FREE";return c}function mark(c:Card,m:Set<string>,n:number){for(let x=0;x<5;x++)for(let y=0;y<5;y++)if(c[x]![y]===n)m.add(`${y}-${x}`)}function lines(m:Set<string>){const out:string[]=[];for(let r=0;r<5;r++)if(Array.from({length:5},(_,c)=>`${r}-${c}`).every(x=>m.has(x)))out.push(`row-${r}`);for(let c=0;c<5;c++)if(Array.from({length:5},(_,r)=>`${r}-${c}`).every(x=>m.has(x)))out.push(`col-${c}`);if(Array.from({length:5},(_,i)=>`${i}-${i}`).every(x=>m.has(x)))out.push("diag-a");if(Array.from({length:5},(_,i)=>`${i}-${4-i}`).every(x=>m.has(x)))out.push("diag-b");return out}
