import { randomInt } from "node:crypto";
import { mkdirSync } from "node:fs";
import { readJsonFileSync as readFileSync, writeJsonFile as writeFileSync } from "../storage/atomic-json.js";
import { plinkoRounds } from "../storage/store-validators.js";
import { dirname } from "node:path";
import type { DiscordUser } from "@iris/shared";
import type { ServerEnv } from "../env.js";
import { AppError } from "../errors.js";
import { reserveCasinoBet, settleCasinoReservation } from "../services/casino-economy.js";
type FetchLike = (input: string | URL, init?: RequestInit) => Promise<Response>;
type Risk = "low" | "medium" | "high"; type Phase = "reserving" | "settling" | "settled";
const tables: Record<Risk, number[]> = { low:[2,1.5,1.2,1,1,.9,.8,.7,.8,.9,1,1.2,1.5,2], medium:[8,3,1.5,1,.5,.3,.2,.1,.2,.3,.5,1,1.5,3,8], high:[22,5,2,.7,.3,.12,0,.12,.3,.7,2,5,22] };
export interface PlinkoRound { dropId: string; discordUserId: string; bet: number; risk: Risk; choices: boolean[] | null; bin: number | null; multiplier: number | null; payout: number | null; wallet: number | null; phase: Phase; }
export interface PlinkoRoundStore { load(): PlinkoRound[]; save(rounds: PlinkoRound[]): void; }
export class FilePlinkoRoundStore implements PlinkoRoundStore { constructor(private readonly filePath:string){} load():PlinkoRound[]{try{const value:unknown=JSON.parse(readFileSync(this.filePath, "utf8", plinkoRounds));if(!Array.isArray(value))throw new Error("Plinko state is invalid.");return value as PlinkoRound[]}catch(error){if(error instanceof Error&&"code" in error&&error.code==="ENOENT")return [];throw error}} save(rounds:PlinkoRound[]):void{mkdirSync(dirname(this.filePath),{recursive:true});writeFileSync(this.filePath, JSON.stringify(rounds), "utf8", plinkoRounds)} }
export class PlinkoService { private readonly rounds:Map<string,PlinkoRound>; constructor(private readonly options:{env:ServerEnv;fetch:FetchLike;store:PlinkoRoundStore;choices?:()=>boolean[]}){this.rounds=new Map(options.store.load().map(round=>[round.dropId,round]))} async reconcileAll(){for(const round of this.rounds.values())if(round.phase!=="settled")await this.resume(round)} async drop(user:DiscordUser,dropId:string,bet:number,risk:Risk):Promise<PlinkoRound>{if(!/^[A-Za-z0-9:_.-]{1,128}$/.test(dropId)||![100,500,1000,2500,5000].includes(bet)||!isRisk(risk))throw new AppError(400,"bad_request","Plinko drop is invalid.");const existing=this.rounds.get(dropId);if(existing){if(existing.discordUserId!==user.id||existing.bet!==bet||existing.risk!==risk)throw new AppError(409,"casino_transaction_conflict","Plinko drop does not match its original request.");await this.resume(existing);return existing}const round:PlinkoRound={dropId,discordUserId:user.id,bet,risk,choices:null,bin:null,multiplier:null,payout:null,wallet:null,phase:"reserving"};this.rounds.set(dropId,round);this.save();await this.resume(round);return round} private async resume(round:PlinkoRound){if(round.phase==="reserving"){const reserve=await reserveCasinoBet({transactionId:`plinko-${round.dropId}`,discordUserId:round.discordUserId,sessionId:`plinko-${round.dropId}`,game:"plinko",bet:round.bet},this.options.env,this.options.fetch);round.wallet=reserve.wallet;round.choices??=this.options.choices?.()??Array.from({length:12},()=>Boolean(randomInt(2)));if(round.choices.length!==12)throw new AppError(500,"internal_error","Plinko path is invalid.");round.bin=round.choices.filter(Boolean).length;round.multiplier=tables[round.risk][round.bin]!;round.payout=Math.floor(round.bet*round.multiplier);round.phase="settling";this.save()}if(round.phase==="settling"){const settled=await settleCasinoReservation(`plinko-${round.dropId}`,{payout:round.payout??0},this.options.env,this.options.fetch);round.wallet=settled.wallet;round.phase="settled";this.save()}} private save(){this.options.store.save([...this.rounds.values()])} }
function isRisk(value:string):value is Risk{return value==="low"||value==="medium"||value==="high"}
