import { randomInt } from "node:crypto";
import { mkdirSync } from "node:fs";
import { readJsonFileSync as readFileSync, writeJsonFile as writeFileSync } from "../storage/atomic-json.js";
import { dirname } from "node:path";
import type { DiscordUser } from "@iris/shared";
import type { ServerEnv } from "../env.js";
import { AppError } from "../errors.js";
import { reserveCasinoBet, settleCasinoReservation } from "../services/casino-economy.js";
type FetchLike=(input:string|URL,init?:RequestInit)=>Promise<Response>;type Phase="reserving"|"active"|"settling"|"settled";type SymbolId="blank"|"moon"|"star"|"rose"|"diamond"|"crown"|"wild";
const weights:Record<SymbolId,number>={blank:38,moon:20,star:15,rose:10,diamond:6,crown:2,wild:9};const pays:Partial<Record<SymbolId,Record<number,number>>>={moon:{4:.5,5:2,6:6},star:{4:.8,5:3,6:9},rose:{4:1.2,5:5,6:18},diamond:{4:2.5,5:10,6:40},crown:{4:10,5:50,6:200}};
export interface ScratchRound{ticketId:string;discordUserId:string;bet:number;symbols:SymbolId[];revealed:number[];phase:Phase;payout:number|null;wallet:number|null;lastActionId:string|null;lastIndex:number|null}
export interface ScratchStore{load():ScratchRound[];save(rounds:ScratchRound[]):void}
export class FileScratchStore implements ScratchStore{constructor(private readonly path:string){}load(){try{const v:unknown=JSON.parse(readFileSync(this.path,"utf8"));if(!Array.isArray(v))throw new Error("Scratch state invalid");return v as ScratchRound[]}catch(e){if(e instanceof Error&&"code" in e&&e.code==="ENOENT")return [];throw e}}save(r:ScratchRound[]){mkdirSync(dirname(this.path),{recursive:true});writeFileSync(this.path,JSON.stringify(r),"utf8")}}
export class ScratchService{private readonly rounds:Map<string,ScratchRound>;constructor(private readonly o:{env:ServerEnv;fetch:FetchLike;store:ScratchStore}){this.rounds=new Map(o.store.load().map(r=>[r.ticketId,r]))}async reconcileAll(){for(const r of this.rounds.values())if(r.phase==="reserving"||r.phase==="settling")await this.resume(r)}async issue(u:DiscordUser,id:string,bet:number){if(!valid(id)||![100,500,1000,2500,5000].includes(bet))throw new AppError(400,"bad_request","Scratch ticket invalid.");const old=this.rounds.get(id);if(old){if(old.discordUserId!==u.id||old.bet!==bet)throw new AppError(409,"casino_transaction_conflict","Scratch ticket does not match.");await this.resume(old);return pub(old)}const r:ScratchRound={ticketId:id,discordUserId:u.id,bet,symbols:Array.from({length:9},pick),revealed:[],phase:"reserving",payout:null,wallet:null,lastActionId:null,lastIndex:null};this.rounds.set(id,r);this.save();await this.resume(r);return pub(r)}async reveal(u:DiscordUser,id:string,actionId:string,index:number){const r=this.require(u,id);if(!valid(actionId)||!Number.isInteger(index)||index<0||index>8)throw new AppError(400,"bad_request","Scratch reveal invalid.");await this.resume(r);if(r.lastActionId===actionId){if(r.lastIndex!==index)throw new AppError(409,"casino_transaction_conflict","Scratch action does not match.");return pub(r)}if(r.phase!=="active"||r.revealed.includes(index))throw new AppError(409,"casino_transaction_conflict","Scratch tile unavailable.");r.lastActionId=actionId;r.lastIndex=index;r.revealed.push(index);if(r.revealed.length===9){r.payout=Math.floor(r.bet*multiplier(r.symbols));r.phase="settling"}this.save();await this.resume(r);return pub(r)}async revealAll(u:DiscordUser,id:string,actionId:string){const r=this.require(u,id);if(!valid(actionId))throw new AppError(400,"bad_request","Scratch reveal invalid.");await this.resume(r);if(r.lastActionId===actionId)return pub(r);if(r.phase!=="active")throw new AppError(409,"casino_transaction_conflict","Scratch ticket unavailable.");r.lastActionId=actionId;r.lastIndex=null;r.revealed=Array.from({length:9},(_,i)=>i);r.payout=Math.floor(r.bet*multiplier(r.symbols));r.phase="settling";this.save();await this.resume(r);return pub(r)}private async resume(r:ScratchRound){if(r.phase==="reserving"){const x=await reserveCasinoBet({transactionId:`scratch-${r.ticketId}`,discordUserId:r.discordUserId,sessionId:`scratch-${r.ticketId}`,game:"scratch",bet:r.bet},this.o.env,this.o.fetch);r.wallet=x.wallet;r.phase="active";this.save()}if(r.phase==="settling"){const x=await settleCasinoReservation(`scratch-${r.ticketId}`,{payout:r.payout??0},this.o.env,this.o.fetch);r.wallet=x.wallet;r.phase="settled";this.save()}}private require(u:DiscordUser,id:string){const r=this.rounds.get(id);if(!r||r.discordUserId!==u.id)throw new AppError(404,"casino_transaction_not_found","Scratch ticket not found.");return r}private save(){this.o.store.save([...this.rounds.values()])}}
function pub(r:ScratchRound){return{...r,symbols:r.phase==="settled"?r.symbols:r.symbols.map((x,i)=>r.revealed.includes(i)?x:null)}}function valid(v:string){return /^[A-Za-z0-9:_.-]{1,128}$/.test(v)}function pick():SymbolId{let n=randomInt(100);for(const [id,w]of Object.entries(weights)as [SymbolId,number][]){n-=w;if(n<0)return id}return"blank"}function multiplier(s:SymbolId[]){const count:Partial<Record<SymbolId,number>>={};let wild=0;for(const x of s){if(x==="wild")wild++;else if(x!=="blank")count[x]=(count[x]??0)+1}let best=0;for(const [id,table]of Object.entries(pays)as [SymbolId,Record<number,number>][])best=Math.max(best,table[Math.min(6,(count[id]??0)+wild)]??0);return best}
