import { randomInt } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import type { DiscordUser } from "@iris/shared";
import type { ServerEnv } from "../env.js";
import { AppError } from "../errors.js";
import { reserveCasinoBet, settleCasinoReservation } from "../services/casino-economy.js";

type FetchLike = (input: string | URL, init?: RequestInit) => Promise<Response>;
type Phase = "reserving" | "tie" | "settling" | "settled";
type Action = "surrender" | "war";
export type WarCard = { rank: string; suit: string };
type PendingAdditionalWager = { actionId: string; transactionId: string; bet: number };
export interface WarRound { roundId:string; discordUserId:string; bet:number; deck:WarCard[]; player:WarCard|null; dealer:WarCard|null; warPlayer:WarCard|null; warDealer:WarCard|null; phase:Phase; payout:number|null; wallet:number|null; label:string|null; wentToWar:boolean; lastActionId:string|null; lastAction:Action|null; pendingAdditionalWager?:PendingAdditionalWager }
export interface WarRoundStore { load():WarRound[]; save(rounds:WarRound[]):void }
export class FileWarRoundStore implements WarRoundStore { constructor(private readonly filePath:string) {} load(){try{const value:unknown=JSON.parse(readFileSync(this.filePath,"utf8"));if(!Array.isArray(value))throw new Error("War state invalid");return value as WarRound[]}catch(error){if(error instanceof Error&&"code" in error&&error.code==="ENOENT")return [];throw error}} save(rounds:WarRound[]){mkdirSync(dirname(this.filePath),{recursive:true});writeFileSync(this.filePath,JSON.stringify(rounds),"utf8")} }

export class WarService {
  private readonly rounds: Map<string, WarRound>;
  constructor(private readonly options:{env:ServerEnv;fetch:FetchLike;store:WarRoundStore;deck?:()=>WarCard[]}) { this.rounds=new Map(options.store.load().map((round)=>[round.roundId,round])); }
  async reconcileAll(){ await Promise.all([...this.rounds.values()].filter((round)=>round.phase==="reserving"||round.phase==="settling"||Boolean(round.pendingAdditionalWager)).map(async(round)=>{try{await this.resume(round)}catch(error){console.error("casino_round_reconcile_failed",{game:"war",roundId:round.roundId,phase:round.phase,errorName:error instanceof Error?error.name:"NonErrorThrown",errorMessage:error instanceof Error?error.message:"unknown reconciliation error"})}})); }
  async deal(user:DiscordUser,id:string,bet:number){ if(!valid(id)||![100,500,1000,2500,5000].includes(bet))throw new AppError(400,"bad_request","War round is invalid."); const existing=this.rounds.get(id); if(existing){if(existing.discordUserId!==user.id||existing.bet!==bet)throw conflict();await this.resume(existing);return existing} const round:WarRound={roundId:id,discordUserId:user.id,bet,deck:this.options.deck?.()??deck(),player:null,dealer:null,warPlayer:null,warDealer:null,phase:"reserving",payout:null,wallet:null,label:null,wentToWar:false,lastActionId:null,lastAction:null};this.rounds.set(id,round);this.save();await this.resume(round);return round; }
  async act(user:DiscordUser,id:string,actionId:string,action:Action){const round=this.require(user,id);if(!valid(actionId)||(action!=="surrender"&&action!=="war"))throw new AppError(400,"bad_request","War action invalid.");if(round.lastActionId===actionId){if(round.lastAction!==action)throw conflict();await this.resume(round);return round}if(round.pendingAdditionalWager||round.phase!=="tie")throw conflict();round.lastActionId=actionId;round.lastAction=action;if(action==="surrender"){round.payout=Math.floor(round.bet/2);round.label="SURRENDER";round.phase="settling";this.save();await this.resume(round);return round}round.pendingAdditionalWager={actionId,transactionId:`war-${round.roundId}-1`,bet:round.bet};this.save();await this.resume(round);return round;}
  private async resume(round:WarRound){if(round.phase==="reserving"){const reserved=await reserveCasinoBet({transactionId:`war-${round.roundId}-0`,discordUserId:round.discordUserId,sessionId:`war-${round.roundId}`,game:"war",bet:round.bet},this.options.env,this.options.fetch);round.wallet=reserved.wallet;round.dealer=draw(round);round.player=draw(round);const player=value(round.player),dealer=value(round.dealer);if(player>dealer){round.payout=round.bet*2;round.label="PLAYER WINS";round.phase="settling"}else if(player<dealer){round.payout=0;round.label="DEALER WINS";round.phase="settling"}else{round.phase="tie";round.label="TIE"}this.save()}if(round.phase==="tie"&&round.pendingAdditionalWager){const pending=round.pendingAdditionalWager;const reserved=await reserveCasinoBet({transactionId:pending.transactionId,discordUserId:round.discordUserId,sessionId:`war-${round.roundId}`,game:"war",bet:pending.bet},this.options.env,this.options.fetch);round.wallet=reserved.wallet;round.wentToWar=true;draw(round);draw(round);draw(round);round.warDealer=draw(round);round.warPlayer=draw(round);round.dealer=round.warDealer;round.player=round.warPlayer;const dealer=value(round.dealer),player=value(round.player);round.payout=player>dealer?Math.floor(round.bet*3.6):player===dealer?round.bet*2:0;round.label=player>dealer?"WAR VICTORY":player===dealer?"WAR PUSH":"WAR DEFEAT";round.pendingAdditionalWager=undefined;round.phase="settling";this.save()}if(round.phase==="settling"){const settled=await settleCasinoReservation(`war-${round.roundId}-0`,{payout:round.payout??0},this.options.env,this.options.fetch);round.wallet=settled.wallet;if(round.wentToWar){round.wallet=(await settleCasinoReservation(`war-${round.roundId}-1`,{payout:0},this.options.env,this.options.fetch)).wallet}round.phase="settled";this.save()}}
  private require(user:DiscordUser,id:string){const round=this.rounds.get(id);if(!round||round.discordUserId!==user.id)throw new AppError(404,"casino_transaction_not_found","War round not found.");return round} private save(){this.options.store.save([...this.rounds.values()])}
}
function deck():WarCard[]{const cards:WarCard[]=[];for(const suit of ["S","H","D","C"])for(const rank of ["2","3","4","5","6","7","8","9","10","J","Q","K","A"])cards.push({rank,suit});for(let index=cards.length-1;index>0;index--){const swap=randomInt(index+1);[cards[index],cards[swap]]=[cards[swap]!,cards[index]!]}return cards} function draw(round:WarRound){const card=round.deck.pop();if(!card)throw new AppError(500,"internal_error","War deck is exhausted.");return card} function value(card:WarCard){return card.rank==="A"?14:card.rank==="K"?13:card.rank==="Q"?12:card.rank==="J"?11:Number(card.rank)} function valid(value:string){return /^[A-Za-z0-9:_.-]{1,128}$/.test(value)} function conflict(){return new AppError(409,"casino_transaction_conflict","War round cannot accept that action.")}
