/* eslint-disable @typescript-eslint/no-explicit-any */
import { randomInt, randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { readJsonFileSync as readFileSync, writeJsonFile as writeFileSync } from "../storage/atomic-json.js";
import { duelRounds } from "../storage/store-validators.js";
import { dirname } from "node:path";
import type { DiscordUser } from "@iris/shared";

const modes = new Set(["roulette", "dice", "blackjack", "war", "baccarat"]);
const ranks = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
const suits = ["S", "H", "D", "C"];
const red = new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
type Duel = Record<string, any>;

export class FileDuelStore { constructor(private readonly path:string) {} load():Duel[]{try{const v=JSON.parse(readFileSync(this.path, "utf8", duelRounds));return Array.isArray(v)?v:[]}catch(e){if(e instanceof Error&&"code" in e&&e.code==="ENOENT")return [];throw e}} save(v:Duel[]){mkdirSync(dirname(this.path),{recursive:true});writeFileSync(this.path, JSON.stringify(v), "utf8", duelRounds)} }
export class DuelService {
  private duels=new Map<string,Duel>();
  constructor(private readonly store:FileDuelStore){for(const duel of store.load())this.duels.set(duel.id,duel)}
  create(user:DiscordUser,room:string,mode:string,glyph:string,queue=false){this.valid(mode);const duel=this.new(user,room,mode,glyph,queue);this.save();return duel}
  queue(user:DiscordUser,room:string,mode:string,glyph:string){this.valid(mode);let duel=[...this.duels.values()].find(x=>x.room===room&&x.queue&&x.mode===mode&&x.status==="waiting"&&x.players[0].id!==user.id);if(!duel)duel=this.new(user,room,mode,glyph,true);else{duel.players.push(this.player(user,glyph));this.start(duel)}this.save();return duel}
  join(user:DiscordUser,room:string,code:string,glyph:string){const duel=[...this.duels.values()].find(x=>x.room===room&&x.code===code&&x.status==="waiting");if(!duel||duel.players.some((p:any)=>p.id===user.id))throw Error("Challenge was not found.");duel.players.push(this.player(user,glyph));this.start(duel);this.save();return duel}
  state(userId:string,id:string){const duel=this.duels.get(id);if(!duel||!duel.players.some((p:any)=>p.id===userId))throw Error("Match was not found.");return duel}
  action(userId:string,id:string,action:any){const d=this.state(userId,id);if(d.status!=="active")throw Error("Match is not active.");if(d.mode==="blackjack"){const hand=d.blackjack.hands[userId];if(!hand||d.blackjack.stood[userId])throw Error("Turn is complete.");if(action.type==="hit"){hand.push(d.deck.pop());if(value(hand)>=21)d.blackjack.stood[userId]=true}else if(action.type==="stand")d.blackjack.stood[userId]=true;else throw Error("Invalid action.");if(Object.values(d.blackjack.stood).every(Boolean))this.resolveBlackjack(d)}else{if(action.type!=="pick"||d.choices[userId])throw Error("Invalid action.");d.choices[userId]={category:String(action.category||""),number:Number.isInteger(action.number)?action.number:null};if(Object.keys(d.choices).length===2)this.resolve(d)}this.save();return d}
  leave(userId:string,id:string){const d=this.state(userId,id);if(d.status==="waiting"){d.status="cancelled"}else if(d.status==="active"){d.winnerId=d.players.find((p:any)=>p.id!==userId)?.id||null;d.status="complete";d.completedAt=Date.now()}this.save();return d}
  claim(userId:string,id:string){const d=this.state(userId,id);if(d.status!=="complete")throw Error("Match is not complete.");d.claimed??=[];const result=d.winnerId===userId?"win":d.winnerId?"loss":"tie";return {alreadyClaimed:d.claimed.includes(userId),result,mode:d.mode,amount:result==="win"?500:result==="tie"?150:0}}
  markClaim(userId:string,id:string){const d=this.state(userId,id);d.claimed??=[];if(!d.claimed.includes(userId)){d.claimed.push(userId);this.save()}}
  private new(u:DiscordUser,room:string,mode:string,glyph:string,queue:boolean){const duel={id:randomUUID(),room,code:this.code(),mode,queue,status:"waiting",players:[this.player(u,glyph)],round:0,maxRounds:mode==="blackjack"?3:5,choices:{},history:[],winnerId:null,completedAt:0,claimed:[]};this.duels.set(duel.id,duel);return duel}
  private player(u:DiscordUser,glyph:string){return {id:u.id,name:u.displayName||u.username,glyph:glyph.slice(0,8),score:0}}
  private start(d:Duel){d.status="active";d.round=d.mode==="blackjack"?0:1;if(d.mode==="blackjack")this.dealBlackjack(d)}
  private resolve(d:Duel){const [a,b]=d.players,points:any={[a.id]:0,[b.id]:0};let out:any={};if(d.mode==="roulette"){const n=randomInt(37);out={number:n};for(const p of d.players){const x=d.choices[p.id];if(hit(n,x.category))points[p.id]++;if(x.number===n)points[p.id]+=3}}else if(d.mode==="dice"){const sum=2+randomInt(6)+randomInt(6);out={sum};for(const p of d.players){const x=d.choices[p.id].category;points[p.id]=x===`exact-${sum}`?3:x==="seven"&&sum===7?2:(x==="low"&&sum<=6)||(x==="high"&&sum>=8)?1:0}}else if(d.mode==="war"){const cards={[a.id]:card(),[b.id]:card()};out={cards};const av=cardValue(cards[a.id]),bv=cardValue(cards[b.id]);if(av!==bv)points[av>bv?a.id:b.id]=1}else{out=baccarat();for(const x of d.players)if(d.choices[x.id].category===out.winner)points[x.id]=out.winner==="tie"?3:1}for(const p of d.players)p.score+=points[p.id];d.history.push({round:d.round,type:d.mode,outcome:out,points});d.choices={};if(d.round>=d.maxRounds)this.finish(d);else d.round++}
  private dealBlackjack(d:Duel){d.deck=deck();d.round++;d.blackjack={hands:{},stood:{}};for(const p of d.players){d.blackjack.hands[p.id]=[d.deck.pop(),d.deck.pop()];d.blackjack.stood[p.id]=value(d.blackjack.hands[p.id])>=21}}
  private resolveBlackjack(d:Duel){const [a,b]=d.players,av=value(d.blackjack.hands[a.id]),bv=value(d.blackjack.hands[b.id]);const winner=av>21?b.id:bv>21?a.id:av===bv?null:av>bv?a.id:b.id;if(winner)d.players.find((p:any)=>p.id===winner).score++;d.history.push({round:d.round,type:"blackjack",winnerId:winner,hands:d.blackjack.hands});if(d.round>=3)this.finish(d);else this.dealBlackjack(d)}
  private finish(d:Duel){d.status="complete";d.completedAt=Date.now();d.winnerId=d.players[0].score===d.players[1].score?null:d.players[0].score>d.players[1].score?d.players[0].id:d.players[1].id}
  private valid(mode:string){if(!modes.has(mode))throw Error("Invalid duel mode.")};private code(){return randomUUID().replace(/-/g,"").slice(0,6).toUpperCase()};private save(){this.store.save([...this.duels.values()])}
}
function deck(){const x=suits.flatMap(s=>ranks.map(r=>({rank:r,suit:s})));for(let i=x.length-1;i;i--){const j=randomInt(i+1);[x[i],x[j]]=[x[j]!,x[i]!]}return x}function card(){return deck()[0]!}function value(cards:any[]){let n=0,a=0;for(const c of cards){if(c.rank==="A"){n++;a++}else n+=["J","Q","K"].includes(c.rank)?10:Number(c.rank)}while(a&&n+10<=21){n+=10;a--}return n}function cardValue(c:any){return c.rank==="A"?14:c.rank==="K"?13:c.rank==="Q"?12:c.rank==="J"?11:Number(c.rank)}function baccaratValue(c:any){return c.rank==="A"?1:["10","J","Q","K"].includes(c.rank)?0:Number(c.rank)}function baccaratTotal(cards:any[]){return cards.reduce((n,c)=>n+baccaratValue(c),0)%10}function baccarat(){const d=deck(),player=[d.pop(),d.pop()],banker=[d.pop(),d.pop()];let p=baccaratTotal(player),b=baccaratTotal(banker),third:number|null=null;if(p<8&&b<8){if(p<=5){const c=d.pop()!;player.push(c);third=baccaratValue(c);p=baccaratTotal(player)}const draw=third===null?b<=5:b<=2||(b===3&&third!==8)||(b===4&&third>=2&&third<=7)||(b===5&&third>=4&&third<=7)||(b===6&&(third===6||third===7));if(draw){banker.push(d.pop()!);b=baccaratTotal(banker)}}return {player,banker,playerTotal:p,bankerTotal:b,winner:p===b?"tie":p>b?"player":"banker"}}function hit(n:number,x:string){return (x==="red"&&red.has(n))||(x==="black"&&n!==0&&!red.has(n))||(x==="odd"&&n%2===1)||(x==="even"&&n!==0&&n%2===0)||(x==="low"&&n>=1&&n<=18)||(x==="high"&&n>=19)}
